#!/usr/bin/env bash

set -e

VERSION="0.3.0"

USAGE="kubelogs [-h] [-n] [-v] -- dump kubernetes pod logs to local files
Options:
    -h, --help           Show this help text
    -n, --namespace      The Kubernetes namespace to list pods. If empty list available namespaces
    -v, --version        Prints the kubelogs version"

# Get namespace list from current context
function select_namespace() {
  NAMESPACE_LIST=(`kubectl get namespaces --output=jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | awk 'NF {print $1; print $1}'`)
  if [[ -z ${NAMESPACE_LIST[@]} ]]; then echo "No namespaces found for context $(kubectl config current-context)!" >&2; exit 1; fi
  NAMESPACE=$(whiptail --noitem --title "Select a namespace" --menu "choose" 16 78 10 "${NAMESPACE_LIST[@]}" 3>&1 1>&2 2>&3)
}

# Get pod list from selected namespace
function select_pods() {
  POD_LIST=(`kubectl get pods --namespace=${NAMESPACE} --output=jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | awk 'NF {print $1; print $1}'`)
  if [[ -z ${POD_LIST[@]} ]]; then echo "No pods found for namespace ${NAMESPACE}!" >&2; exit 1; fi
  PODS=(`whiptail --noitem --title "Select pods from namespace ${NAMESPACE}" --checklist "choose" 16 78 10 "${POD_LIST[@]}" 3>&1 1>&2 2>&3`)
  # Remove quotes from array elements
  PODS=("${PODS[@]//\"/}")
}

# Select output directory
function select_output_dir() {
  OUTPUT_DIR=$(whiptail --inputbox "Enter a local directory for output file(s):" 8 78 --title "Directory" 3>&1 1>&2 2>&3)
  while [[ ! -w $OUTPUT_DIR ]] || [[ ! -d $OUTPUT_DIR ]]
  do
    whiptail --title "Output directory error" --yesno "Invalid directory or insuficient permissions! Try again?" 8 78
    OUTPUT_DIR=$(whiptail --inputbox "Enter a local directory for output file(s):" 8 78 --title "Directory" 3>&1 1>&2 2>&3)
  done
}

# Get container logs from NAMESPACE/PODS
function get_container_logs() {
    #TIMESTAMP="$(date +"%Y%m%d_%H%M%S")"
    for pod in "${PODS[@]}"
    do
      CONTAINERS=(`kubectl get pods --namespace=${NAMESPACE} ${pod} --output=jsonpath='{.spec.containers[*].name}'`)
      for container in "${CONTAINERS[@]}"
      do
        echo "Getting ${pod}/${container} logs..."
        kubectl logs --timestamps --namespace=${NAMESPACE} ${pod} --container=${container} >> "$OUTPUT_DIR/${pod}_${container}.log" || { printf "\nError while getting log content!" >&2; exit 1; }
      done
    done
}

if [ "$#" -ne 0 ]; then
  while [ "$#" -gt 0 ]
  do
    case "$1" in
    -h|--help)
          echo "$USAGE"
          exit 0
          ;;
    -v|--version)
          echo "$VERSION"
          exit 0
          ;;
    -n|--namespace)
          if [ -z "$2" ]; then
            select_namespace # Call select_namespace if parameter --namespace is empty
          else
            NAMESPACE="$2"
          fi
          ;;
    --)
          break
          ;;
    -*)
          echo "Invalid option '$1'. Use --help to see the valid options" >&2
          exit 1
          ;;
    # an option argument, continue
    *)  ;;
    esac
    shift
  done
fi

# Call select_namespace function if $NAMESPACE is empty
if [[ -z "$NAMESPACE" ]]; then select_namespace; fi

# Call select_pod function
select_pods

# Call select_dir function
select_output_dir

# Call get_container_logs function
get_container_logs
