#!/usr/bin/env bash
VERSION="0.3.0"

USAGE="kubelogs [-h] [-n] [-v] -- dump kubernetes pod logs to local file
Options:
    -h, --help           Show this help text
    -n, --namespace      The Kubernetes namespace to list pods. If empty list available namespaces
    -v, --version        Prints the kubelogs version"

function select_namespace() {
  #Get namespace names for current context
  NAMESPACE_LIST=(`kubectl get namespaces --output=jsonpath='{.items[*].metadata.name}'`)

  if [[ -z ${NAMESPACE_LIST[@]} ]]; then echo "No namespaces found for this context!" >&2; exit 1; fi

  printf "Choose a namespace:\n"
  PS3='Namespace: '
  select option in "${NAMESPACE_LIST[@]}" "CANCEL"
  do
    if [[ ! -z $option ]] && [[ $option != "CANCEL" ]]; then
      NAMESPACE=$option
      echo "Namespace selected is $NAMESPACE"
      break
    elif [[ $option = "CANCEL" ]]; then
      echo "Bye!"
      exit
    else
      echo "Invalid namespace!"
    fi
  done
}

function select_pod() {
  #Get pod names from namespace
  POD_LIST=(`kubectl get pods --namespace=$NAMESPACE --output=jsonpath='{.items[*].metadata.name}'`)

  if [[ -z ${POD_LIST[@]} ]]; then echo "No pods found for namespace $NAMESPACE!" >&2; exit 1; fi

  printf "\nChoose a pod:\n"
  PS3='Pod: '
  select option in "${POD_LIST[@]}" "CANCEL"
  do
    if [[ ! -z $option ]] && [[ $option != "CANCEL" ]]; then
      POD=$option
      echo "Pod selected is $POD"
      break
    elif [[ $option = "CANCEL" ]]; then
      echo "Bye!"
      exit
    else
      echo "Invalid Pod!"
    fi
  done
}

function select_container() {
  #Get container names from prod
  CONTAINER_LIST=(`kubectl get pods --namespace=$NAMESPACE $POD --output=jsonpath='{.spec.containers[*].name}'`)

  if [[ -z ${CONTAINER_LIST[@]} ]]; then echo "No containers found for pod $POD!" >&2; exit 1; fi

  #If pod have just 1 container, use it and return the function
  if [[ ${#CONTAINER_LIST[@]} -eq 1 ]]; then
    CONTAINER=${CONTAINER_LIST[0]}
    echo "Using the $CONTAINER unique container"
    return
  fi

  printf "\nChoose a container:\n"
  PS3='Container: '
  select option in "${CONTAINER_LIST[@]}" "CANCEL"
  do
    if [[ ! -z $option ]] && [[ $option != "CANCEL" ]]; then
      CONTAINER=$option
      echo "Container selected is $CONTAINER"
      break
    elif [[ $option = "CANCEL" ]]; then
      echo "Bye!"
      exit
    else
      echo "Invalid container!"
    fi
  done
}

if [ "$#" -ne 0 ]; then
  while [ "$#" -gt 0 ]
  do
    case "$1" in
    -h|--help)
          echo "$USAGE"
          exit 0
          ;;
    -v|--version)
          echo "$VERSION"
          exit 0
          ;;
    -n|--namespace)
          if [ -z "$2" ]; then
            select_namespace #Call select_namespace if parameter --namespace is empty
          else
            NAMESPACE="$2"
          fi
          ;;
    --)
          break
          ;;
    -*)
          echo "Invalid option '$1'. Use --help to see the valid options" >&2
          exit 1
          ;;
    # an option argument, continue
    *)  ;;
    esac
    shift
  done
fi


if [[ -z "$NAMESPACE" ]]; then select_namespace; fi #Call select_namespace function if $NAMESPACE is empty

select_pod #Call select_pod function

select_container #Call select_container function

read -p "Type a local directory for output file: " OUTPUT_DIR
while [[ ! -w $OUTPUT_DIR ]] || [[ ! -d $OUTPUT_DIR ]]
do
  printf "Invalid directory or insuficient permissions!\n" >&2
  read -p "Enter a local directory for output file: " OUTPUT_DIR
done

TIMESTAMP="$(date +"%Y%m%d_%H%M%S")"
OUTPUT_NAME="$POD"_"$CONTAINER"_"$TIMESTAMP".log
OUTPUT_FILE=$OUTPUT_DIR/$OUTPUT_NAME

#Get logs from pod and save to local file
kubectl logs --timestamps --namespace=$NAMESPACE $POD -c $CONTAINER > $OUTPUT_FILE || { printf "\nError to get log content!" >&2; exit 1; }
echo "Log file saved in $OUTPUT_FILE"
